Question 1

In [2]:
import numpy as np

np.tile([5, 15, 25], (5, 2))

array([[ 5, 15, 25,  5, 15, 25],
       [ 5, 15, 25,  5, 15, 25],
       [ 5, 15, 25,  5, 15, 25],
       [ 5, 15, 25,  5, 15, 25],
       [ 5, 15, 25,  5, 15, 25]])

Question 2

In [19]:
dim = 9
arr0 = np.zeros((dim, dim))
for i in range(dim // 4 + 1):
  for j in range(0 + 2 * i, dim - 2 * i):
    arr0[0 + 2 * i][j] = 1
    arr0[dim - 1 - 2 * i][j] = 1
    arr0[j][0 + 2 * i] = 1
    arr0[j][dim - 1 - 2 * i] = 1

print(arr0)

arr1 = np.zeros((3, 3))
arr1[1][1] = 1
arr1 = np.pad(arr1, 1, mode='constant', constant_values=1)
arr1 = np.pad(arr1, 1, mode='constant', constant_values=0)
arr1 = np.pad(arr1, 1, mode='constant', constant_values=1)

print(arr1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Question 3

In [22]:
chessboard = np.full((8, 8), ' ')
chessboard[[0, 7]] = ['R', 'H', 'B', 'Q', 'K', 'B', 'H', 'R']
chessboard[[1, 6]] = ['P'] * 8

print(chessboard)

[['R' 'H' 'B' 'Q' 'K' 'B' 'H' 'R']
 ['P' 'P' 'P' 'P' 'P' 'P' 'P' 'P']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['P' 'P' 'P' 'P' 'P' 'P' 'P' 'P']
 ['R' 'H' 'B' 'Q' 'K' 'B' 'H' 'R']]


Question 4

In [43]:
arr = np.arange(1, 101)
arr[0] = 0
for i in [2, 3, 5, 7]:
  arr[2 * i - 1::i] = 0
arr = arr[arr > 0]

print(arr)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


Question 5