Question 1

In [46]:
import numpy as np

arr = np.tile(np.array([5, 15, 25]), (5, 2))

print(arr)


[[ 5 15 25  5 15 25]
 [ 5 15 25  5 15 25]
 [ 5 15 25  5 15 25]
 [ 5 15 25  5 15 25]
 [ 5 15 25  5 15 25]]


Question 2

In [47]:
dim = 9
arr0 = np.zeros((dim, dim))
for i in range(dim // 4 + 1):
    for j in range(0 + 2 * i, dim - 2 * i):
        arr0[0 + 2 * i][j] = 1
        arr0[dim - 1 - 2 * i][j] = 1
        arr0[j][0 + 2 * i] = 1
        arr0[j][dim - 1 - 2 * i] = 1

print(arr0)

arr1 = np.zeros((3, 3))
arr1[1][1] = 1
arr1 = np.pad(arr1, 1, mode='constant', constant_values=1)
arr1 = np.pad(arr1, 1, mode='constant', constant_values=0)
arr1 = np.pad(arr1, 1, mode='constant', constant_values=1)

print(arr1)


[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Question 3

In [48]:
chessboard = np.full((8, 8), ' ')
chessboard[[0, 7]] = ['R', 'H', 'B', 'Q', 'K', 'B', 'H', 'R']
chessboard[[1, 6]] = ['P'] * 8

print(chessboard)


[['R' 'H' 'B' 'Q' 'K' 'B' 'H' 'R']
 ['P' 'P' 'P' 'P' 'P' 'P' 'P' 'P']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['P' 'P' 'P' 'P' 'P' 'P' 'P' 'P']
 ['R' 'H' 'B' 'Q' 'K' 'B' 'H' 'R']]


Question 4

In [49]:
primes = np.arange(1, 101)
primes[0] = 0
for i in [2, 3, 5, 7]:
    primes[2 * i - 1::i] = 0
primes = primes[primes > 0]

print(primes)


[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


Question 5

In [50]:
import pandas as pd

incomes=[40000,35000,45000,300000,90000,400000,115000,25000,80000]
heights=[60.5,59.6,None,73.4,65.9,72.4,None,66.8,None]

df = pd.DataFrame({'Income': incomes, 'Height': heights})
df.loc[df['Income'] > 150000, 'Income'] = 150000
df['Height'].fillna(df['Height'].mean().round(2), inplace=True)

df


Income  Height
0   40000   60.50
1   35000   59.60
2   45000   66.43
3  150000   73.40
4   90000   65.90
5  150000   72.40
6  115000   66.43
7   25000   66.80
8   80000   66.43

Question 6

In [51]:
filepath = './data/numbers.csv'
numbers = pd.read_csv(filepath)

numbers['median'] = numbers.median(axis=1)

print(numbers)
print('Max value:', numbers['median'].max(), 'at index', numbers['median'].idxmax())
print('Median of row medians:', numbers['median'].median())
print('Median of all values:', numbers.stack().median())


    num1  num2  num3  num4  num5  num6  num7  num8  num9  num10  median
0     80    99    17    33    49    94    96    70    37     51    60.5
1     54    63    30     8     3    73    52    84     8     42    47.0
2     93    82    22    55    80    49    44    67    63     55    59.0
3     74    31    54    75    11    50    59    85    15     66    56.5
4     75    34     4    32    80     8    28    36    85     27    33.0
5     92    15    30    68    68    91    31    44    21     22    37.5
6     84     5    32    15    50    96    60    23    12     84    41.0
7     35    49    75    77    45    75    30    84    35     10    47.0
8     52    30     4    72    76    26    48    16    24     53    39.0
9     17    75    70    16    23    16    35    65    21     67    29.0
10    86    19    65    55    15    95    30    95    69     81    67.0
11    29    23    97    19    29    36    14    11    62     15    26.0
12    63    49    62    58    46    48    75    97    76     86 

Question 7

In [52]:
filepath = './data/meals.csv'
meals = pd.read_csv(filepath)

print(meals.groupby('cuisine')['price'].max().sort_values(ascending=False).head())


cuisine
Korean     $99.80
Spanish    $99.73
Thai       $98.90
Mexican    $98.42
Chinese    $98.38
Name: price, dtype: object


Question 8

In [53]:
filepath = './data/meals.csv'
meals = pd.read_csv(filepath)

meals['price'] = pd.to_numeric(meals['price'].str.replace('$', '', regex=False))
meals.drop('id', axis=1).groupby('cuisine').describe().round(2).sort_values(('price', 'mean'), ascending=False)


price                                                
          count   mean    std   min    25%    50%    75%    max
cuisine                                                        
Indian    107.0  55.74  26.59  6.89  32.06  56.18  78.20  96.59
Chinese   102.0  52.77  27.31  5.20  27.62  51.38  75.69  98.38
Lebanese  100.0  52.53  25.84  5.45  29.96  51.38  73.38  98.02
Greek     105.0  52.28  26.21  6.54  30.81  51.61  73.90  98.37
Spanish    84.0  52.01  28.74  7.01  29.38  46.64  79.20  99.73
French     83.0  51.86  25.88  5.93  29.49  54.51  68.43  97.38
Mexican   109.0  51.34  26.27  5.31  33.25  50.69  73.88  98.42
Korean    112.0  50.85  29.71  5.17  22.35  49.60  79.58  99.80
Thai      109.0  50.67  26.98  6.42  28.83  50.46  76.24  98.90
Italian    89.0  48.76  26.24  5.63  30.53  46.56  69.74  97.62

Question 9

In [54]:
ownership = pd.DataFrame(
    {
        "name": ["Sam","Eric","Audrey","Isabel","Anika","Nathan","Catherine",
                 "Chris","Julie","Stephen","John","Jim","Mary"],
        "cars": [
            ["Ford","Toyota","Volkswagen","Nissan","Hyundai"],
            ["Toyota","Chevrolet","Nissan","Jaguar","Volkswagen","General Motors"],
            ["Jeep","Ford","Chrysler","Fiat","General Motors","Volkswagen"],
            ["Rolls Royce","Bentley","Porsche","BMW"],
            ["Toyota", "Chevrolet", "Hyundai","Fiat"],
            ["Trabant", "Skoda", "Mercedes","Honda","General Motors"],
            ["Renault", "Geely", "Volvo","Skoda","Suzuki","Honda"],
            ["Ford","Toyota","Tata","Suzuki","Mercedes"],
            ["Fiat", "Rolls Royce", "Tata","BMW"],
            ["Chrysler", "Jaguar", "Volvo","Fiat"],
            ["Geely", "Jeep", "Fiat"],
            ["Chevrolet", "Volvo", "Fiat","Geely","Ford"],
            ["Toyota", "Fiat", "Chrysler","Bentley","Porsche","Renault"],
        ],
    }
)

print('Most common manufacturer:', ownership.explode('cars')['cars'].value_counts().idxmax())
print('Least common manufacturer:', ownership.explode('cars')['cars'].value_counts().idxmin())
print('Person who owned fewest cars:', ownership.explode('cars')['name'].value_counts().idxmin())


Most common manufacturer: Fiat
Least common manufacturer: Trabant
Person who owned fewest cars: John


Question 10

In [55]:
filepath = './data/stock_prices.csv'
stocks = pd.read_csv(filepath)

stocks['spread'] = stocks['high'] - stocks['low']
stocks.sort_values(['ticker', 'spread'], inplace=True)
stocks


date        open        high         low       close   adj close  \
25  2022-10-04  145.029999  146.220001  144.259995  146.100006  146.100006   
31  2022-10-12  139.130005  140.360001  138.160004  138.339996  138.339996   
27  2022-10-06  145.809998  147.539993  145.220001  145.429993  145.429993   
34  2022-10-17  141.070007  142.899994  140.270004  142.410004  142.410004   
30  2022-10-11  139.899994  141.350006  138.220001  138.979996  138.979996   
..         ...         ...         ...         ...         ...         ...   
61  2022-10-24  205.820007  213.500000  198.589996  211.250000  211.250000   
47  2022-10-04  250.520004  257.500000  242.009995  249.440002  249.440002   
54  2022-10-13  208.300003  222.990005  206.220001  221.720001  221.720001   
44  2022-09-29  282.760010  283.649994  265.779999  268.209991  268.209991   
55  2022-10-14  224.009995  226.259995  204.160004  204.990005  204.990005   

       volume ticker     spread  
25   87830100   AAPL   1.960007  
31   70433700   AAPL   2.199997  
27   68402200   AAPL   2.319992  
34   85250900   AAPL   2.629990  
30   77033700   AAPL   3.130005  
..        ...    ...        ...  
61  100446800   TSLA  14.910004  
47  109578500   TSLA  15.490005  
54   91483000   TSLA  16.770004  
44   77620600   TSLA  17.869995  
55   93898700   TSLA  22.099991  

[132 rows x 9 columns]