In [ ]:
def cap_and_join(*args):
  return " ".join(map(lambda x: x.capitalize(), args))

cap_and_join("wassup", "shawty", "whats", "poppin")

'Wassup Shawty Whats Poppin'

In [ ]:
from functools import reduce

factorial = lambda n: reduce(lambda x, y: x * y, range(1, n + 1))

print(factorial(6))

720


In [ ]:
double = lambda n: n * 2
square = lambda n: n ** 2

print(double(16))
print(square(16))

32
256


In [ ]:
from functools import reduce
product = lambda *args: reduce(lambda x, y: x * y, args)

print(product(2, 2, 6, 5))

120


In [ ]:
# define a class
class Dog:
  def __init__(self,name,weight,age,got_rabies_shot):
    self.name=name
    self.weight=weight
    if age<=29: # validate
      self.age=age
    else:
      raise ValueError("That is too old.")
    self.got_rabies_shot=got_rabies_shot
  def __str__(self):
    s=self.name+" is a dog that weighs "
    s+=str(self.weight)+" pounds and is "
    s+=str(self.age)+" years old;"
    if self.got_rabies_shot:
      s+=" vaccinated for Rabies."
    else:
      s+=" not vaccinated for Rabies."
    return
  def got_vaccine(self):
    self.got_rabies_shot = True
  def compare_age(self, dog2):
    if self.age == dog2.age:
      print(self.name + " and " + dog2.name + " are the same age.")
    elif self.age > dog2.age:
      print(self.name + " is older than " + dog2.name)
    else:
      print(dog2.name + " is older than " + self.name)

In [ ]:
import math
class Point: # class definition, starts with keyword "class"
    '''Creates a point on a coordinate plane with values x and y.'''

    def __init__(self, x, y): # method called when an object is created
        '''Defines x and y variables'''
        self.x = x
        self.y = y

    def __str__(self): # method called when an object is printed
        return "Point(%s,%s)"%(self.x, self.y)
    import math
    def manhattanDistance(self, other):
      dx = abs(self.x - other.x)
      dy = abs(self.y - other.y)
      return dx + dy
    def distance(self, other):
      dx = abs(self.x - other.x)
      dy = abs(self.y - other.y)
      return math.sqrt(dx**2 + dy**2)
    def manhattanDistance(self, other):
      return abs(self.x - other.x) + abs(self.y - other.y)


p=Point(0,0)
q=Point(3,4)
print(p.x)
print(p.y)
print(p)
print(q)
print(p.manhattanDistance(q))

0
0
Point(0,0)
Point(3,4)
7


In [ ]:
class Circle:
  def __init__(self, pt, r):
    self.center = pt
    self.radius = r
    self.area = math.pi * (r ** 2)
    self.perimeter = math.pi * 2 * r

  def intersect(self, other):
    return self.center.distance(other.center) <= (self.radius + other.radius)



In [ ]:
class clock_iterator:
  def __init__(self, start):
    self.cur = start
  def __iter__(self):
    return self
  def __next__(self):
    ret = self.cur
    if self.cur == 23:
      self.cur = 0
    else:
      self.cur += 1
    return ret


In [ ]:
[i for i in "The rain in Spain is mainly on the plain." if i.lower() in "aeiou"]
{i for i in "The rain in Spain is mainly on the plain." if i.lower() in "aeiou"}


{'a', 'e', 'i', 'o'}

In [ ]:
def ME(a, b):
  return (a * b) ** 3

ME = lambda a, b: (a * b) ** 3

ME(2, 2)

64

In [ ]:
def fib():
  x = 0
  y = 1
  while True:
    yield x
    x, y = y, x + y

i = 0
for i in fib():
  print(i)
  if i > 5:
    break
  i += 1


0
1
1
2
3
5
8


In [ ]:
ge = (i ** 2 for i in range(100))
print(list(filter(lambda i: i % 10 == 1, ge)))

[1, 81, 121, 361, 441, 841, 961, 1521, 1681, 2401, 2601, 3481, 3721, 4761, 5041, 6241, 6561, 7921, 8281, 9801]


In [ ]:
def stopwatch():
  hr, min, sec = 0, 0, 0
  while True:
    yield hr, min, sec
    sec += 1
    if sec == 60:
      sec = 0
      min += 1
    if min == 60:
      min = 0
      hr += 1
    if hr == 24:
      hr = 0

sw = stopwatch()
for i in range(1000000):
  hours, mins, secs = next(sw)
print(hours,mins,secs)

13 46 39


In [ ]:
import numpy as np
arr = np.arange(3, 85, 3).reshape(4, 7)
print(arr)
print(arr[1:3, 3:5])

[[ 3  6  9 12 15 18 21]
 [24 27 30 33 36 39 42]
 [45 48 51 54 57 60 63]
 [66 69 72 75 78 81 84]]
[[33 36]
 [54 57]]


In [3]:
import pandas as pd
import numpy as np

prime = lambda n: not([i for i in range(2, int(n ** 0.5) + 1) if n % i == 0])
df = pd.DataFrame(np.arange(2, 18).reshape(4, 4))

print(df.applymap(prime))

       0      1      2      3
0   True   True  False   True
1  False   True  False  False
2  False   True  False   True
3  False  False  False   True


In [ ]:
df = pd.read_csv('weight-height.csv')
print(df['Height'].round(0).value_counts())
print(df['Height'][df["Gender"]=="Female"].round(0).value_counts())
print(df['Height'][df["Gender"]=="Male"].round(0).value_counts())